### ISSUE TITLE
knn_pytorch.knn(ref, query, inds)

### ISSUE THREAD

**Issue by taylorlulu** [rhett-chen/graspness_implementation#20]
I'm currently using the python2.7.12, torch 1.8.1 and cuda 11.1
![image](https://github.com/rhett-chen/graspness_implementation/assets/49311079/f53c0be9-fdcc-4be4-9a8e-2275a356f7d3)
I encountered this problem when I'm trying to run the command:
```
cd dataset
python generate_graspness.py --dataset_root ./data3/graspnet --camera_type kinect
```

It says that the error was caused by 

```
knn_pytorch.knn(ref, query, inds)
error in knn: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/home/lu/anaconda3/envs/GSNet/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-b2a1f9446434>", line 1, in <module>
    knn_pytorch.knn(ref, query, inds)
RuntimeError: aborting at /home/lu/Desktop/Code/1_grasping_pose/graspness_implementation/knn/src/knn.h:47
```

I thought this might be the problem of the version of cuda and pytorch. So I tried torch1.9.0+cu111. But it still wouldn't work, as it said:
```
Traceback (most recent call last):
  File "/home/lu/anaconda3/envs/GSNet/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-b2a1f9446434>", line 1, in <module>
    knn_pytorch.knn(ref, query, inds)
RuntimeError: Unrecognized tensor type ID: Autocast
```
[](url)
I guess this problem may be caused by knn_pytorch library as it shows the error in the same line. 
In the [pytorch_knn_cuda](https://github.com/chrischoy/pytorch_knn_cuda) repository, which needs to make.
But in the knn folder, the author had already provided the build folder and the result of made. Could it be the problem?
I would appreciate a lot if anyone could help.

**Comment by rhett-chen** [comment]
Hi, I have tried torch1.8.0 and torch1.9.0, and they both work well. I guess it may be an issue with the GPU driver or CUDA installation being incompatible with the GPU. If you can't fix it, you can try installing pytorch3d and replacing knn_pytorch with pytorch3d.knn.

**Comment by taylorlulu** [comment]
I've solved the problem by migrate the program to the server. Thanks a lot!
